UPDATE tpost SET EDIT_TYPE='publish' WHERE EDIT_TYPE IS NULL;
UPDATE tpost SET UUID_USER_PUBLISH='0' WHERE UUID_USER_PUBLISH IS NULL;
UPDATE tpost SET UUID_USER='0' WHERE UUID_USER IS NULL;
UPDATE tpost SET UUID_USER_CREATE='0' WHERE UUID_USER_CREATE IS NULL;
UPDATE tpost SET DATE_PUBLISH=CURRENT_TIMESTAMP WHERE DATE_PUBLISH IS NULL;

COMMIT WORK;